name: Run tests
on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Setup and run tests
      run: |
        set -xe
        #Install pre-reqs
        sudo apt update
        sudo apt install -y git curl openjdk-11-jdk python3

        #Install Nextflow
        curl -s https://get.nextflow.io | bash
        chmod a+x nextflow
        cp nextflow /usr/local/bin

        python3 --version

        pip install pdm
      
        #Git setup
        # git config --global user.email "it-support@gpas.global"
        # git config --global user.name "gpas-github-bot"

        # #Get the gpas repo and set it up
        # git clone https://${{secrets.PAT_TOKEN}}@github.com/GlobalPathogenAnalysisService/gpas.git

        # cd gpas




