name: Run tests
on: [push]

jobs:
  test:
    name: Run tests
    container:
        image: python:3.11

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: gpas
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install SOPS
      run: |
        sudo apt-get update && sudo apt-get install age -y
        # Download the binary
        curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
        mv sops-v3.8.1.linux.amd64 /usr/local/bin/sops
        chmod +x /usr/local/bin/sops
        mkdir -p ~/.config/sops/age
        echo "${{ secrets.AGE_DEV_KEY }}" > "$HOME/.config/sops/age/keys.txt"
    
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.11'
            
    - name: Setup and run tests
      run: |
        set -xe
        #Install pre-reqs
        sudo apt update
        sudo apt install -y git curl openjdk-11-jdk jq
        pip install pdm

        #Install Nextflow
        curl -s https://get.nextflow.io | bash 2> /dev/null
        chmod a+x nextflow
        cp nextflow /usr/local/bin

        #Git setup
        git config --global user.email "it-support@gpas.global"
        git config --global user.name "gpas-github-bot"

        #Get the gpas repo and set it up
        git clone https://${{secrets.PAT_TOKEN}}@github.com/GlobalPathogenAnalysisService/gpas.git

        cd gpas

        pdm install

        #Setup the API
        #Note that as this runs in the bg, it doesn't always start in order here
        pdm run serve > pdm-serve.log 2>&1  &
        sleep 10
        echo Started API
        pdm run bootstrap

        #Give it some data and check we can access
        cd .. 

        #Ensure we have enough runs to test what we want
        bash test/bootstrap.sh

        cat gpas/pdm-serve.log

        #Build test cases with known distances
        python test/build-test-set.py

        #Run without queuing
        bash test/run-synchronous.sh

        #Run with queuing
        sudo bash test/run-asynchronous.sh

        #Test it produces expected results
        bash test/test-eq.sh
        





